# Media Enhanced Swiftlet Cargo Config
# Real-time Communication of Media over the Internet using QUIC

# Cargo Command Aliases that have partial usefulness
[alias]
run-quic-example = "run -p swiftlet_quic --example simple"
run-binaural-example = "run -p swiftlet_binaural --example demo"
cross-windows-x64 = "zigbuild --target x86_64-pc-windows-gnu"
cross-windows-x64m = "zigbuild --target x86_64-pc-windows-msvc"
cross-windows-arm = "zigbuild --target aarch64-pc-windows-msvc"
cross-linux-x64 = "zigbuild --target x86_64-unknown-linux-gnu"
cross-linux-arm = "zigbuild --target aarch64-unknown-linux-gnu"
cross-macos-arm = "zigbuild --target aarch64-apple-darwin"
cross-macos-x64 = "zigbuild --target x86_64-apple-darwin"

#[env]
#RUST_BACKTRACE="1"

# OLD STUFF TO BE REMOVED IN THE FUTURE
#CARGO_TARGET_DIR = "./target/$(rustc -vV:target_arch)/"
#COREAUDIO_SDK_PATH="MacOSX.sdk"

#[target.x86_64-unknown-linux-gnu]
#rustflags = ["-G MinGW Makefiles"]

