# Media Enhanced Swiftlet Cargo Config
# Real-time Communication of Media over the Internet using QUIC

# Cargo Command Aliases that have partial usefulness
[alias]
build-windows-x64 = "build --target x86_64-pc-windows-gnu"
build-windows-arm64 = "build --target aarch64-pc-windows-msvc"
build-macos-arm64 = "build --target aarch64-apple-darwin"
build-macos-x64 = "build --target x86_64-apple-darwin"
build-linux-x64 = "build --target x86_64-unknown-linux-gnu"
build-linux-arm64 = "build --target aarch64-unknown-linux-gnu"
run-quic-example = "run -p swiftlet_quic --example simple"
run-binaural-example = "run -p swiftlet_binaural --example demo"
